baseURL: "https://darek.blog"
languageCode: en-us
title: darek.blog
theme: "PaperMod"
enableEmoji: true
enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

taxonomies:
  category: categories
  series: series
  tag: tags

params:
    homeInfoParams:
        Title: Hi there... // CzeÅ›Ä‡... ğŸ‘‹ ğŸ‘ ğŸ™‚ 
        Content: I am glad you are here. This blog is about **education, technology, young people** and many other topics I am interested in. Enjoy it and get in touch! // CieszÄ™ siÄ™, Å¼e tu jesteÅ›. Ten blog jest o **edukacji, technologiach i mÅ‚odych ludziach** i wielu innych tematach, ktÃ³rymi siÄ™ interesujÄ™. Korzystaj i odezwij siÄ™ w razie potrzeby!
