baseURL: "https://darek.blog"
title: darek.blog
theme: "PaperMod"
enableEmoji: true
enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

taxonomies:
  category: categories
  series: series
  tag: tags

languages:
    en:
        languageName: "English"
        weight: 1
        
    pl:
        languageName: "Polski"
        languageAltTitle: Polish
        weight: 2
        title: darek.blog
        homeInfoParams:
            Title: "CzeÅ›Ä‡... ðŸ™‚ "
            Content: CieszÄ™ siÄ™, Å¼e tu jesteÅ›. Ten blog jest o prawach czÅ‚owieka, edukacji, technologiach, mÅ‚odych ludziach i wielu innych tematach, ktÃ³rymi siÄ™ interesujÄ™. Korzystaj i skontaktuj siÄ™ ze mnÄ…!

        menu:
            main:
                - name: Tags
                  url: tags
                  weight: 10
        
menu:
    main:
        - identifier: tags
          name: Tags
          url: /tags/
          weight: 40

params:
    homeInfoParams:
        Title: Hi all there... ðŸ™‚ 
        Content: I am glad you are here. This blog is about **human rights, education, technology, young people** and many other topics I am interested in. Enjoy it and get in touch! 

    socialIcons:
    - name: LinkedIn
      url: "https://www.linkedin.com/in/dariusz-grzemny-39716a3/"
    - name: RSS
      url: "index.xml"

    defaultTheme: auto
    # disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: true
    # disableSpecial1stPost: true
    displayFullLangName: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowToc: false

    # defaultTheme: light
    # defaultTheme: dark
    defaultTheme: auto # to switch between dark or light according to browser theme

